sudo: required
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

jobs:
  include:
    - &build
      stage: Build
      script:
      - yarn lint
      - yarn build
      node_js: '10'

    - <<: *build
      node_js: '8'

